# Generated by Django 5.2.11 on 2026-03-01 01:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GratitudeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('entry', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'gratitude entries',
                'ordering': ['date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DailyInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('serenity_level', models.PositiveIntegerField(default=5, help_text='Serenity level 1-10')),
                ('was_resentful', models.BooleanField(default=False)),
                ('resentful_details', models.TextField(blank=True)),
                ('was_selfish', models.BooleanField(default=False)),
                ('selfish_details', models.TextField(blank=True)),
                ('was_dishonest', models.BooleanField(default=False)),
                ('dishonest_details', models.TextField(blank=True)),
                ('did_pray', models.BooleanField(default=False)),
                ('did_meditate', models.BooleanField(default=False)),
                ('spiritual_notes', models.TextField(blank=True)),
                ('mood', models.PositiveIntegerField(default=5, help_text='Mood level 1-10')),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_inventories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'daily inventories',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
