# Generated by Django 5.2.11 on 2026-03-01 01:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, max_length=200)),
                ('how_harmed', models.TextField(help_text='How did you harm this person?')),
                ('willingness_level', models.IntegerField(choices=[(1, 'Not willing'), (2, 'Somewhat willing'), (3, 'Willing'), (4, 'Very willing'), (5, 'Ready now')], default=3)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amends_people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Amend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('letter_drafted', 'Letter Drafted'), ('discussed', 'Discussed with Sponsor'), ('amend_made', 'Amend Made'), ('ongoing', 'Ongoing / Living Amend')], default='not_started', max_length=20)),
                ('anger_letter', models.TextField(blank=True, help_text='Private anger letter — DO NOT SEND')),
                ('apology_letter', models.TextField(blank=True, help_text='Apology / amends letter')),
                ('actionable_amends', models.TextField(blank=True, help_text='Concrete actions to make amends')),
                ('sponsor_feedback', models.TextField(blank=True, help_text='Feedback from your sponsor')),
                ('post_amend_reflection', models.TextField(blank=True, help_text='How did making the amend feel?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amends', to='amends.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
